package com.springboot.getwork.service;

import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.springboot.getwork.model.Company;
import com.springboot.getwork.repository.CompanyRepository;

@Service
public class CompanyServiceImpl implements CompanyService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CompanyRepository companyRepository;

    @Override
    public Company getCompanyInfo(Integer company_id) {
        return companyRepository.findById(company_id).get();
    }

    @Override
    @Transactional(rollbackOn = Exception.class)
    public Company getCompanyByEmailPassword(String email,String password){
        Company company =  companyRepository.findCompanyByEmailPassword(email,password);
        return company;
    }

    @Override
    public List<Company> getAll() {
        List<Company> list = new ArrayList<>();
        companyRepository.findAll().iterator().forEachRemaining(list::add);
        return list;
    }

    /* (non-Javadoc)
     * @see com.rococo.springboot.service.UserService#registerPerson(com.rococo.springboot.model.User)
     */
    @Override
    public void registerCompany(Company company) {
        companyRepository.save(company);
    }

}
