package com.springboot.getwork.service;

import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.springboot.getwork.model.Company;
import com.springboot.getwork.model.JobRequest;
import com.springboot.getwork.model.Contract;
import com.springboot.getwork.repository.ContractRepository;

@Service
public class ContractServiceImpl implements ContractService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ContractRepository contractRepository;

    @Override
    public List<Contract> getAllByJobRequestId(JobRequest jobRequest){
        return contractRepository.findAllByJobRequestId(jobRequest.getId());
    }

    @Override
    public void createContract(Contract contract){
        contractRepository.save(contract);
    }

    @Override
    public List<Contract> getContractsByNumberOrStatus(String key){
        return contractRepository.findContractsByContractNumberOrStatus(key);
    }
}
